### ISSUE TITLE
interpret u8g2.clearBuffer(); as tft.fillScreen(TFT_BLACK) 

### ISSUE THREAD

**Issue by ClemensGruber** [Bodmer/U8g2_for_TFT_eSPI#1]
For backward compatibility it could make sense to interpret 

`u8g2.clearBuffer(); `
as
`tft.fillScreen(TFT_BLACK) `

and ignore `u8g2.sendBuffer();`

**Comment by Bodmer** [comment]
Hi, I am not familiar with the U8g2 library. Can you provide an example sketch for TFT_eSPI that uses the clearBuffer command. I am guessing that command is intended to clear a RAM screen buffer so I am not sure why fillScreen is a direct substitute.

**Comment by Bodmer** [comment]
Closing until it is clear why this is useful.

**Comment by ClemensGruber** [comment]
In the initial code I've used there was a command `u8g2.clearBuffer()` that throw an compiling error with `u8f.clearBuffer()`. It was used to "erase" a former filled screen, I think similar to `tft.fillScreen(TFT_BLACK) `

So I did a search and found on the U8g2 reference page https://github.com/olikraus/u8g2/wiki/u8g2reference#cleardisplay also 

```
clear
clearBuffer
clearDisplay
```

For `clear `vs. `clearBuffer `see https://github.com/olikraus/u8g2/issues/911 . I tried all three clearing methods but all are not supported by U8g2_for_TFT_eSPI

Same -- compiling error -- happens for 
```
sendBuffer
drawLine
drawFrame
drawBox
drawXBM
```

in the sketch I'm experimenting atm.

**Comment by Bodmer** [comment]
As far as I understand the original U8g2 used a display buffer, like a sprite, that the text is rendered to, then the buffer is sent to the screen. This allows displays like the SSD1306 to be supported with improved rendering speeds. On low memory processors like the UNO the buffer was "paged" to use less RAM, This meant that display updates had to be done in a multipass loop.

As far as I am aware the Adafruit variant which U8g2_for_TFT_eSPI was ported from does not use a buffer, it writes pixels direct to the display. So U8g2_for_TFT_eSPI is really only the font rendering engine from U8g2. This means that the clear functions have no purpose in U8g2_for_TFT_eSPI thus were never implemented by the [original author here](https://github.com/olikraus/U8g2_for_Adafruit_GFX).  Clearly this makes porting code intended for U8g2 more invasive but there is little that can be done about this.

The U8g2 functions supported can be found in the [header file here](https://github.com/Bodmer/U8g2_for_TFT_eSPI/blob/master/src/U8g2_for_TFT_eSPI.h), i.e the equivalents of [these GFX variant](https://github.com/Bodmer/U8g2_for_TFT_eSPI#command-reference) functions.

**Comment by ClemensGruber** [comment]
Many thanks for the explanation. The code I'm experimenting with is based on the "normal" u8g2 lib (from Oliver Kraus also), see https://github.com/olikraus/u8g2 and has this clear and send buffer elements. So this may explain the absence of this functions. I found some clearing functions in the underlaying Adafruit lib e.g. https://github.com/adafruit/Adafruit_SSD1306 so my use case -- switching from an OLED with u8g2 as lib to a TFT display with less code change -- seems to be a bit other than the inteded one based on Adafruit display libs.
