### ISSUE TITLE
Enhancement Request: make u8g2_for_TFT_eSPI available for sprites

### ISSUE THREAD

**Issue by andreash-esp** [Bodmer/U8g2_for_TFT_eSPI#2]
Hi,

is it possible to extend this great enhancement to TFT_eSPI to the sprites as well?

Regards
Andreas

**Comment by Bodmer** [comment]
I expect you can use:
u8f.begin(spr)

And:
u8f.begin(tft)

As you wish to direct the font rendering to a sprite or the tft. However I have not tried this!

**Comment by andreash-esp** [comment]
Thanks for your reply. I must have missed something during my tests.
This is in fact working fine!

**Comment by Bodmer** [comment]
I will add an example. Thanks for raising this.
