### ISSUE TITLE
Display unicode fonts

### ISSUE THREAD

**Issue by NodeMCU-Kang** [Bodmer/U8g2_for_TFT_eSPI#3]
Hello,

I have some unicode fonts for U8g2, it's great for you to provide this library.

I tried to use the fonts with U8g2_for_TFT_eSPI, the first issue I met is that U8g2_for_TFT_eSPI does not support enableUTF8Print(), so I commented it out. Then compiling and building were OK. But it only displayed the blue background with black blocks on the tft.setCursor() positions.

Is it caused by not running enableUTF8Print()? Any way to get the unicode fonts displayed?

 <pre><code>
#include "SPI.h"
#include "TFT_eSPI.h"
#include "U8g2_for_TFT_eSPI.h"

TFT_eSPI tft = TFT_eSPI(); // tft instance
U8g2_for_TFT_eSPI u8f; // U8g2 font instance

void setup() {
  tft.begin(tft);
  tft.fillScreen(TFT_BLUE); 

  // U8g2_for_TFT_eSPI does not support enableUTF8Print(), so comment it out
  //u8f.enableUTF8Print(); // enable UTF8 support for the Arduino print() function
  
  u8f.setFont(u8g2_font_unifont_t_chinese1);
  u8f.setFontDirection(0);
  u8f.setCursor(0, 15);
  u8f.print("第一行"); // Chinese Unicode chars
  u8f.setCursor(0, 40);
  u8f.print("連接位址"); // Chinese Unicode chars
}
void loop() {
}
</code></p

**Comment by NodeMCU-Kang** [comment]
I added some codes and the Chinese chars displayed correctly.

 <pre><code>
#include "SPI.h"
#include "TFT_eSPI.h"
#include "U8g2_for_TFT_eSPI.h"

TFT_eSPI tft = TFT_eSPI();   // tft instance
U8g2_for_TFT_eSPI u8f;       // U8g2 font instance

void setup() {
  tft.begin();
  tft.fillScreen(TFT_BLUE);

  u8f.begin(tft);                     // connect u8g2 procedures to TFT_eSPI
  u8f.setFontMode(0);                 // use u8g2 none transparent mode
  u8f.setFontDirection(0);            // left to right (this is default)
  u8f.setForegroundColor(TFT_GREEN);  // apply color
  u8f.setBackgroundColor(TFT_BLUE);
  u8f.setFont(u8g2_font_unifont_t_chinese1);
  u8f.setCursor(0, 40);
  u8f.print("連接位址"); // Chinese Unicode chars
}
void loop() {
} 
</code></p

**Comment by Bodmer** [comment]
See here:
https://github.com/olikraus/U8g2_for_Adafruit_GFX#differences-to-u8g2

Note that UTF8 is enabled by default for print so the extra command is not needed.

**Comment by NodeMCU-Kang** [comment]
> See here: https://github.com/olikraus/U8g2_for_Adafruit_GFX#differences-to-u8g2
> 
> Note that UTF8 is enabled by default for print so the extra command is not needed.

Thank you, your libraries are all very helpful.
