### ISSUE TITLE
Can you continue to Start this project ?

### ISSUE THREAD

**Issue by neoworld** [Bodmer/U8g2_for_TFT_eSPI#4]
We need it

**Comment by Bodmer** [comment]
I do not understand the issue. Please elaborate.

**Comment by neoworld** [comment]
Hello, thank you for your reply. The situation is as follows: I have a project that I would like to use TFT_ ESPI to drive the screen instead of using the built-in driver method of U8g2, but I also need to use the Chinese font function supported by U8g2, so I hope to use U8g2_ For_ TFT_ ESPI can be directly implemented, just like U8g2_ For_ Adafruit_ GFX did the same, and please add U8g2_ For_ TFT_ Write down the usage of eSPI clearly...thx

**Comment by Bodmer** [comment]
The examples have already been updated to use the TFT_eSPI library, see here:
https://github.com/Bodmer/U8g2_for_TFT_eSPI/blob/master/examples/Shennong/Shennong.ino
